In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size

9

In [7]:
A[1, 2]

23

In [8]:
A[1][2]

23

In [9]:
A[0][0]

11

In [10]:
A[0][0:2]

array([11, 12])

In [11]:
A[1:3, 2]

array([23, 33])

In [12]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [14]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [15]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [16]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [17]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [20]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [22]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [23]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [24]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [25]:

C.T

array([[1, 2, 3],
       [1, 2, 3]])